FROM gocd/gocd-agent
MAINTAINER IS

RUN curl -fsSL https://get.docker.com/ | sh
RUN apt-get update && \ 
    apt-get -y install python-pip 
RUN pip install docker-compose
RUN usermod -aG docker go
RUN mkdir -p /var/lib/go-agent/pipelines && chown -R go:go /var/lib/go-agent/pipelines
RUN echo go ALL=NOPASSWD: /usr/bin/docker >> /etc/sudoers
RUN echo go ALL=NOPASSWD: /usr/local/bin/docker-compose >> /etc/sudoers

VOLUME "/var/run/docker.sock"
