ci-server:
  image: gocd/gocd-server
  ports:
    - 8153:8153
    - 8154:8154

ci-agent:
  Dockerfile: Dockerfile.agent
  build: ci-agent
  environment:
    GO_SERVER: 192.168.99.101
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
