ci-server:
  image: gocd/gocd-server
  ports:
    - 8153:8153
    - 8154:8154

ci-agent:
  dockerfile: Dockerfile.agent
  build: .
  environment:
    GO_SERVER: 192.168.99.101
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/lib/go-agent/pipelines:/var/lib/go-agent/pipelines:rw
