FROM gocd/gocd-agent
MAINTAINER IS

RUN curl -fsSL https://get.docker.com/ | sh
RUN apt-get -y install python-pip 
RUN pip install docker-compose
RUN groupadd docker
RUN usermod -aG docker go
RUN echo go ALL=NOPASSWD: /usr/bin/docker >> /etc/sudoers
RUN echo go ALL=NOPASSWD: /usr/local/bin/docker-compose >> /etc/sudoers

VOLUME "/var/run/docker.sock"
