nginx:
  build: .
  ports:
    - 80:80
  volumes:
  - /Users/inny/Documents/testing-the-untestable/demo/agent/pipelines/testing/demo/ci/go-agent/pipelines/testing/demo/nginx-conf/:/etc/nginx/sites-enabled
  - /Users/inny/Documents/testing-the-untestable/demo/agent/pipelines/testing/demo/ci/go-agent/pipelines/testing/demo/nginx-html/:/www/data
  links:
  - backend:www.testing-backend.com

backend:
  build: backend
  ports:
    - 9292:9292

spec:
  dockerfile: Dockerfile.spec
  build: .
  volumes:
  - ./demo:/src
  links:
  - nginx:www.testing-sample.com
