nginx:
  build: .
  ports:
    - 80:80

spec:
  dockerfile: Dockerfile.spec
  build: .
  volumes:
  - ./:/src
  links:
  - nginx:www.iso-sample.com

backend:
  build: backend
  ports:
    - 9292:9292

watchtower:
  image: centurylink/watchtower
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  command: --no-pull
