nginx:
  build: .
  ports:
    - 80:80
  volumes:
  - ./nginx-conf/:/etc/nginx/sites-enabled
  - ./nginx-html/:/www/data
  links:
  - backend:www.testing-backend.com

backend:
  build: backend
  ports:
    - 9292:9292

spec:
  dockerfile: Dockerfile.spec
  build: .
  volumes:
  - ./:/src
  links:
  - nginx:www.testing-sample.com
