nginx:
  build: .
  ports:
    - 80:80
  volumes:
  - ./nginx-conf/:/etc/nginx/sites-enabled
  - ./nginx-html/:/www/data
  links:
  - backend:www.iso-backend.com

spec:
  dockerfile: Dockerfile.spec
  build: .
  volumes:
  - ./:/src
  links:
  - nginx:www.iso-sample.com

backend:
  build: backend
  ports:
    - 9292:9292

ci:
  image: gocd/gocd-server
  ports:
    - 8153:8153
    - 8154:8154

ci-agent:
  build: ci-agent
  environment:
    GO_SERVER: 192.168.99.100
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
